# Generated by Django 5.1.7 on 2025-05-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
        ('users', '0003_user_address_user_city_user_countrycode_user_gender_and_more'),
    ]

    operations = [
    ]
