# Generated by Django 5.1.7 on 2025-05-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
